#pragma once

#include "OpenKNXHardware.h"

#ifdef OKNXHW_REG1_BASE_V1
    #define REG1_APP_PIN1 29
    #define REG1_APP_PIN2 28
    #define REG1_APP_PIN3 27
    #define REG1_APP_PIN4 26
    #define REG1_APP_PIN5 18
    #define REG1_APP_PIN6 17
    #define REG1_APP_PIN7 16

    #define SENSOR1_SDA_TX_PIN REG1_APP_PIN2
    #define SENSOR1_SCL_RX_PIN REG1_APP_PIN1
    #define SENSOR2_SDA_TX_PIN REG1_APP_PIN4
    #define SENSOR2_SCL_RX_PIN REG1_APP_PIN3
    #define BINARY_INPUT1_PIN REG1_APP_PIN7
    #define BINARY_INPUT2_PIN REG1_APP_PIN6
    #define BINARY_INPUT3_PIN REG1_APP_PIN5

    #define OPENKNX_BI_GPIO_PINS BINARY_INPUT1_PIN, BINARY_INPUT2_PIN, BINARY_INPUT3_PIN
    #define OPENKNX_BI_GPIO_COUNT 3
    #define OPENKNX_BI_PULSE -1
    #define OPENKNX_BI_PULSE_PAUSE_TIME 0
    #define OPENKNX_BI_PULSE_WAIT_TIME 0
    #define OPENKNX_BI_ONLEVEL HIGH
#endif

#ifdef SMARTMF_METER_REG2
    #define PROG_LED_PIN 11
    #define PROG_LED_PIN_ACTIVE_ON HIGH
    #define INFO_LED_PIN 10
    #define INFO_LED_PIN_ACTIVE_ON HIGH
    #define PROG_BUTTON_PIN 14
    #define PROG_BUTTON_PIN_INTERRUPT_ON FALLING
    #define SAVE_INTERRUPT_PIN 8
    #define KNX_UART_RX_PIN 1
    #define KNX_UART_TX_PIN 0
    #define HARDWARE_NAME "SMARTMF-METER-REG2"
    #define OPENKNX_BI_GPIO_PINS 26, 27
    #define OPENKNX_BI_GPIO_COUNT 2
    #define OPENKNX_BI_PULSE -1
    #define OPENKNX_BI_PULSE_PAUSE_TIME 0
    #define OPENKNX_BI_PULSE_WAIT_TIME 0
#endif
