#pragma once
#include "HardwareConfig.h"

#define FIRMWARE_NAME "Zaehlermodul"

#ifdef DEVICE_PIPICO_BCU_CONNECTOR
    #define OPENKNX_BI_GPIO_PINS 3, 4, 5, 9, 10
    #define OPENKNX_BI_GPIO_COUNT 5
    #define OPENKNX_BI_PULSE -1
    #define OPENKNX_BI_PULSE_PAUSE_TIME 0
    #define OPENKNX_BI_PULSE_WAIT_TIME 0
    #define OPENKNX_BI_ONLEVEL HIGH
#endif

#ifdef DEVICE_SEN_UP1_8XTH
    #define OPENKNX_BI_GPIO_PINS OKNXHW_SENSOR_A1_SCL_PIN, OKNXHW_SENSOR_A2_SDA_PIN, OKNXHW_SENSOR_B1_SCL_PIN, OKNXHW_SENSOR_B2_SDA_PIN, OKNXHW_SENSOR_C1_SCL_PIN
    #define OPENKNX_BI_GPIO_COUNT 5
    #define OPENKNX_BI_PULSE -1
    #define OPENKNX_BI_PULSE_PAUSE_TIME 0
    #define OPENKNX_BI_PULSE_WAIT_TIME 0
    #define OPENKNX_BI_ONLEVEL HIGH
#endif

#ifdef DEVICE_REG1_SEN_MULTI
    #define OPENKNX_BI_GPIO_PINS OKNXHW_REG1_APP_SEN_MULTI_BINARY_INPUT1_PIN, OKNXHW_REG1_APP_SEN_MULTI_BINARY_INPUT2_PIN, OKNXHW_REG1_APP_SEN_MULTI_BINARY_INPUT3_PIN
    #define OPENKNX_BI_GPIO_COUNT 3
    #define OPENKNX_BI_PULSE -1
    #define OPENKNX_BI_PULSE_PAUSE_TIME 0
    #define OPENKNX_BI_PULSE_WAIT_TIME 0
    #define OPENKNX_BI_ONLEVEL OKNXHW_REG1_APP_SEN_MULTI_BINARY_INPUT_ONLEVEL
#endif

#ifdef DEVICE_SMARTMF_1TE_BE_3CH
    #define OPENKNX_BI_GPIO_PINS SMARTMF_BE1_PIN, SMARTMF_BE2_PIN, SMARTMF_BE3_PIN
    #define OPENKNX_BI_GPIO_COUNT 3
#endif

#ifdef DEVICE_SMARTMF_2SML_3BE
    #define OPENKNX_BI_GPIO_PINS SMARTMF_BE1_PIN, SMARTMF_BE2_PIN, SMARTMF_BE3_PIN
    #define OPENKNX_BI_GPIO_COUNT 3
#endif